import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { createApp, nextTick, type App } from 'vue'
import i18n from '@/i18n'
import SaleManagerModal from './SaleManagerModal.vue'
import SalesManagementView from '@/views/SalesManagementView.vue'
import { saleError, type ManagedSale, type SaleListing } from '@/services/pdvManagement'
const mocks=vi.hoisted(()=>({ detail:vi.fn(),preview:vi.fn(),commit:vi.fn(),list:vi.fn(),options:vi.fn(), auth:{isOwner:true,ownSales:false} }))
vi.mock('@/stores/auth',()=>({useAuthStore:()=>mocks.auth}))
vi.mock('@/services/pdvManagement',async original=>({...await original<object>(),pdvManagementAPI:mocks}))
vi.mock('vue-router',()=>({useRouter:()=>({push:vi.fn()})}))
vi.mock('@/services/api',()=>({default:{},inventoryAPI:{},pdvAPI:{}}))
let app:App|null=null,root:HTMLElement|null=null
const fixture=():ManagedSale=>({id:'sale-1',vendedor_id:'user-1',cliente_id:null,cliente_nome:'Cliente exemplo',subtotal_gs:'300',desconto_gs:'0',total_gs:'300',refunded_gs:'0',fiado_reversed_gs:'0',status:'completed',stock_applied:true,notas:null,version:1,created_at:'2026-10-07T13:00:00-03:00',deleted_at:null,seller:'Lucas',actor:'Lucas',can_manage:true,payments:[],events:[],payment_difference_gs:'0',items:[{id:'line-1',item_id:'product-1',item_name:'Camiseta',item_sku:'SKU-P',item_category:null,item_color:'Azul',item_size:'P',quantity:3,returned_quantity:'0',unit_price_gs:100,original_price_gs:null,discount_gs:0,total_gs:300,is_avulso:false,location:'loja'}]})
async function flush(){for(let n=0;n<6;n++){await nextTick();await Promise.resolve()}}
const button=(name:string)=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent?.trim()===name)!
async function click(name:string){const b=button(name);expect(b,`Missing ${name}`).toBeTruthy();b.click();await flush()}
async function mount(page=false){root=document.createElement('div');document.body.append(root);app=createApp(page?SalesManagementView:SaleManagerModal,page?{}:{saleId:'sale-1',sellers:[{id:'user-1',name:'Lucas'}]}).use(i18n);app.mount(root);await flush()}
beforeEach(()=>{vi.clearAllMocks();mocks.auth.isOwner=true;mocks.auth.ownSales=false;i18n.global.locale.value='pt';mocks.detail.mockResolvedValue(fixture());mocks.options.mockResolvedValue({sellers:[]});mocks.preview.mockResolvedValue({operation:'return',reason:'Peça devolvida',plan_token:'a'.repeat(64),before_total_gs:'300',after_total_gs:'200',refund_gs:'100',fiado_credit_gs:'0',cash_refund_gs:'100',stock:[],fiado:[],returns:[],warnings:[],payment_notice:'Estorno registrado no ERP. A devolução por dinheiro, Pix ou cartão é realizada fora do sistema.'});mocks.commit.mockResolvedValue({ok:true,sale_id:'sale-1'})})
afterEach(()=>{app?.unmount();root?.remove();app=null;i18n.global.locale.value='pt'})
describe('Sale management',()=>{
  it('hides all management actions for an employee even if stale data says can_manage',async()=>{mocks.auth.isOwner=false;await mount();expect(button('Editar venda')).toBeUndefined();expect(button('Excluir venda')).toBeUndefined();expect(button('Estorno integral')).toBeUndefined();expect(document.body.textContent).toContain('Camiseta')})
  it('freezes a reviewed partial return and retries an uncertain result with the same idempotency key',async()=>{await mount();await click('Devolução parcial');const qty=document.querySelector('input[type=number]') as HTMLInputElement;qty.value='1';qty.dispatchEvent(new Event('input',{bubbles:true}));const reason=document.querySelector('textarea')!;reason.value='Peça devolvida';reason.dispatchEvent(new Event('input',{bubbles:true}));await flush();await click('Revisar alterações');expect(mocks.preview).toHaveBeenCalledWith('sale-1',expect.objectContaining({lines:[{line_id:'line-1',quantity:1,restock:true}]}));expect(button('Confirmar operação').disabled).toBe(true);const confirm=document.querySelector('.confirm-line input') as HTMLInputElement;confirm.click();await flush();mocks.commit.mockRejectedValueOnce(new Error('Network'));await click('Confirmar operação');expect(button('Voltar à edição').disabled).toBe(true);const first=mocks.commit.mock.calls[0][1];await click('Tentar a mesma confirmação');expect(mocks.commit.mock.calls[1][1]).toEqual(first);expect(mocks.detail).toHaveBeenCalledTimes(2)})
  it('requires a new preview after a stale revision conflict',async()=>{await mount();await click('Estorno integral');const reason=document.querySelector('textarea')!;reason.value='Conferência de teste';reason.dispatchEvent(new Event('input',{bubbles:true}));await flush();await click('Revisar alterações');(document.querySelector('.confirm-line input') as HTMLInputElement).click();await flush();mocks.commit.mockRejectedValueOnce({response:{status:409,data:{detail:'Confira uma nova prévia'}}});await click('Confirmar operação');expect(button('Confirmar operação')).toBeUndefined();expect(button('Revisar alterações')).toBeDefined();expect(document.querySelector('[role=alert]')?.textContent).toContain('nova prévia')})
  it('translates the management interface and displays response failures rather than zero sales',async()=>{mocks.list.mockRejectedValue(new Error('offline'));await mount(true);expect(document.querySelector('[role=alert]')).not.toBeNull();expect(document.querySelector('.sale-summary')).toBeNull();i18n.global.locale.value='es';await flush();expect(document.body.textContent).toContain('Ventas registradas en el PDV');i18n.global.locale.value='en';await flush();expect(document.body.textContent).toContain('Sales recorded in POS')})
  it('discards a detail response after the modal is closed',async()=>{let resolve!:(v:ManagedSale)=>void;mocks.detail.mockReturnValue(new Promise<ManagedSale>(r=>resolve=r));await mount();app?.unmount();app=null;resolve(fixture());await flush();expect(document.querySelector('.sale-dialog')).toBeNull()})
})
