databases:
  - name: erp-eleven-db
    databaseName: eleven
    user: postgres
    region: oregon
    plan: free

services:
  # Backend API Service
  - type: web
    runtime: python
    name: erp-eleven-backend
    buildCommand: pip install -r backend/requirements.txt
    preDeployCommand: cd backend && python init_db.py
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erp-eleven-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # Frontend Static Site
  - type: web
    name: erp-eleven-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://erp-eleven-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html