services:
  # PostgreSQL Database
  - type: pserv
    name: erp-eleven-db
    env: docker
    plan: free
    region: oregon
    databases:
      - name: eleven
        user: postgres

  # Backend API Service
  - type: web
    name: erp-eleven-backend
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11"
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    preDeployCommand: |
      python -c "import psycopg2; conn = psycopg2.connect('$DATABASE_URL'); cursor = conn.cursor(); cursor.execute(open('../postgres.sql').read()); conn.commit(); conn.close()" || echo "Database already initialized"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erp-eleven-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # Frontend Static Site
  - type: web
    name: erp-eleven-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://erp-eleven-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html