databases:
  - name: erp-eleven-db
    databaseName: eleven
    region: sao-paulo
    plan: free

services:
  # Backend API Service
  - type: web
    runtime: python
    name: erp-eleven-backend
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    region: sao-paulo
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erp-eleven-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # Frontend Web Service
  - type: web
    name: erp-eleven-frontend
    runtime: node
    region: sao-paulo
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.19.0  
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: erp-eleven-backend
          property: host